set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(MAIN_DIR "${CMAKE_CURRENT_SOURCE_DIR}/..")
set(EXECUTABLE_OUTPUT_PATH ${MAIN_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${MAIN_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${MAIN_DIR})
set(SRC_DIR "${MAIN_DIR}/src")
set(TMP_DIR "${MAIN_DIR}/tmp")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(COMPILE_MODE "debug")
else()
    set(COMPILE_MODE "release")
endif()

message(STATUS "Building [${COMPILE_MODE}]")
